/**
 * harness-pool.ts — shared player-pool loading for the realism and growth
 * harnesses, in TWO modes:
 *
 *  - REAL (default): pipeline/seeds/players.sql joined to real club squads
 *    via the HUMAN-populated cache CSV (fbref_id → Squad). This is the
 *    authoritative pool for acceptance runs, and it cannot run in CI because
 *    the cache is deliberately uncommitted (DECISIONS.md).
 *  - FIXTURE (--fixture): engine/harness-fixture.json — a committed, stable
 *    stride-sample of the real league (~24 clubs across the quality range,
 *    ≤18 players each) generated by make-harness-fixture.ts. Stable and
 *    representative is the bar, not realistic: enough spread that a
 *    quality-ordering inversion or a growth-compounding runaway still trips
 *    the gates. CI runs this mode as a REGRESSION TRIPWIRE; it is not a
 *    substitute for the real-pool run before an engine/growth PR merges.
 *
 * Regenerate the fixture (locally, cache present) when seeds/players.sql
 * changes materially: node make-harness-fixture.ts
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Attributes } from './engine-types.ts';

const HERE = new URL('.', import.meta.url).pathname;
const SEED_PATH = join(HERE, '..', 'pipeline', 'seeds', 'players.sql');
const STANDARD_CSV = join(HERE, '..', 'pipeline', 'cache', 'csv', 'big5_player_standard.csv');
export const FIXTURE_PATH = join(HERE, 'harness-fixture.json');

export interface HarnessPlayer {
  name: string;
  position: string;
  heightCm: number;
  birthDate: string;
  marketValue: number;
  minutes: number;
  attributes: Attributes;
}

export interface HarnessFixture {
  source: string;
  note: string;
  clubs: Array<{ name: string; players: HarnessPlayer[] }>;
}

// ── real mode: players.sql + cache-CSV squad join ────────────────────────────

interface SeedRow extends HarnessPlayer {
  fbrefId: string;
}

function loadSeed(): SeedRow[] {
  const out: SeedRow[] = [];
  const row = /^INSERT INTO players .*? VALUES \('(.*?)', '(.*?)', '(\w+)', (\d+), \d+, '.*?', (\d+), '(\{.*?\})', '\{.*?\}', '(\{.*\})'\)/;
  for (const line of readFileSync(SEED_PATH, 'utf8').split('\n')) {
    const m = row.exec(line);
    if (!m) continue;
    const meta = JSON.parse(m[7].replace(/''/g, "'"));
    out.push({
      name: m[1].replace(/''/g, "'"),
      birthDate: m[2],
      position: m[3],
      heightCm: Number(m[4]),
      marketValue: Number(m[5]),
      attributes: JSON.parse(m[6]) as Attributes,
      minutes: Number(meta.minutes ?? 0),
      fbrefId: String(meta.fbref_id ?? ''),
    });
  }
  return out;
}

/** minimal CSV row iterator with quote handling (engine has zero deps) */
function* csvRows(text: string): Generator<string[]> {
  let field = '';
  let rowAcc: string[] = [];
  let inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (c === '"') inQ = false;
      else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ',') { rowAcc.push(field); field = ''; }
    else if (c === '\n' || c === '\r') {
      if (field !== '' || rowAcc.length) { rowAcc.push(field); yield rowAcc; }
      field = ''; rowAcc = [];
      if (c === '\r' && text[i + 1] === '\n') i++;
    } else field += c;
  }
  if (field !== '' || rowAcc.length) { rowAcc.push(field); yield rowAcc; }
}

function loadSquadByFbrefId(): Map<string, string> {
  let text: string;
  try {
    text = readFileSync(STANDARD_CSV, 'utf8');
  } catch {
    console.error(
      `real-pool mode needs ${STANDARD_CSV} for the fbref→squad join — the cache is a HUMAN-populated ` +
      'artifact (pipeline/MAPPING.md), deliberately uncommitted. In CI, run with --fixture instead.',
    );
    process.exit(2);
  }
  const rows = csvRows(text);
  const header = rows.next().value as string[];
  const idx = (name: string): number => header.findIndex((h) => h === name);
  const [iSquad, iUrl, iSeason, iMin] = [idx('Squad'), idx('Url'), idx('Season_End_Year'), idx('Min_Playing')];
  const fbref = /\/players\/([0-9a-f]{8})/;
  const best = new Map<string, { squad: string; minutes: number }>();
  for (const r of rows) {
    if (iSeason >= 0 && r[iSeason] !== '2025') continue;
    const m = fbref.exec(r[iUrl] ?? '');
    if (!m) continue;
    const minutes = Number(r[iMin] || 0);
    const prev = best.get(m[1]);
    if (!prev || minutes > prev.minutes) best.set(m[1], { squad: r[iSquad] ?? '', minutes });
  }
  return new Map([...best].map(([id, v]) => [id, v.squad]));
}

// ── the one entry point ──────────────────────────────────────────────────────

/** club name → players. Fixture mode reads the committed JSON; real mode joins the cache. */
export function loadClubPools(fixture: boolean): Map<string, HarnessPlayer[]> {
  if (fixture) {
    const parsed = JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as HarnessFixture;
    return new Map(parsed.clubs.map((c) => [c.name, c.players]));
  }
  const squadOf = loadSquadByFbrefId();
  const byClub = new Map<string, HarnessPlayer[]>();
  for (const p of loadSeed()) {
    const squad = squadOf.get(p.fbrefId);
    if (!squad) continue;
    if (!byClub.has(squad)) byClub.set(squad, []);
    const { fbrefId: _drop, ...player } = p;
    byClub.get(squad)!.push(player);
  }
  return byClub;
}

export const fixtureFlag = (): boolean => process.argv.includes('--fixture');
