"""Seed SQL + review reports."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Dict, List


def sql_quote(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def player_insert(p: Dict) -> str:
    cols = "(full_name, birth_date, position, height_cm, weight_kg, foot, market_value, attributes, physical, source_meta)"
    vals = ", ".join([
        sql_quote(p["full_name"]),
        sql_quote(p["birth_date"]),
        sql_quote(p["position"]),
        str(p["height_cm"]),
        str(p["weight_kg"]),
        sql_quote(p["foot"]),
        str(p["market_value"]),
        sql_quote(json.dumps(p["attributes"])),
        sql_quote(json.dumps(p["physical"])),
        sql_quote(json.dumps(p["source_meta"])),
    ])
    return (
        f"INSERT INTO players {cols} VALUES ({vals})\n"
        "ON CONFLICT (full_name, birth_date) DO UPDATE SET"
        " position = EXCLUDED.position, height_cm = EXCLUDED.height_cm,"
        " weight_kg = EXCLUDED.weight_kg, foot = EXCLUDED.foot,"
        " market_value = EXCLUDED.market_value, attributes = EXCLUDED.attributes,"
        " physical = EXCLUDED.physical, source_meta = EXCLUDED.source_meta;"
    )


def write_seed_sql(path: Path, players: List[Dict]) -> None:
    lines = [
        "-- generated by pipeline/run.py — do not edit by hand",
        f"-- {len(players)} players, Big-5 leagues",
        "BEGIN;",
        *[player_insert(p) for p in players],
        "COMMIT;",
    ]
    path.write_text("\n".join(lines) + "\n")


_BLOCKS = " ▁▂▃▄▅▆▇█"


def _histogram(values: List[int]) -> str:
    buckets = [0] * 20
    for v in values:
        buckets[max(1, min(20, v)) - 1] += 1
    peak = max(buckets) or 1
    return "".join(_BLOCKS[round(8 * b / peak)] for b in buckets)


def write_distribution_report(path: Path, players: List[Dict], attr_order: List[str]) -> None:
    by_pos: Dict[str, List[Dict]] = defaultdict(list)
    for p in players:
        by_pos[p["position"]].append(p)

    lines = [
        "# Attribute distribution report",
        "",
        f"{len(players)} players. Histograms span attribute values 1→20, bar height ∝ count.",
        "",
    ]
    for attr in attr_order:
        lines.append(f"## {attr}")
        lines.append("")
        lines.append("| position | n | histogram (1→20) | mean |")
        lines.append("| --- | --- | --- | --- |")
        for pos in ("GK", "DF", "MF", "FW"):
            vals = [p["attributes"][attr] for p in by_pos.get(pos, [])]
            if not vals:
                continue
            mean = sum(vals) / len(vals)
            lines.append(f"| {pos} | {len(vals)} | `{_histogram(vals)}` | {mean:.1f} |")
        lines.append("")
        top = sorted(players, key=lambda p: (-p["attributes"][attr], -p["minutes"]))[:20]
        lines.append("Top 20: " + ", ".join(
            f"{p['full_name']} ({p['position']}, {p['attributes'][attr]})" for p in top
        ))
        lines.append("")
    path.write_text("\n".join(lines) + "\n")
